### PR TITLE
consistent puzzle size description

### PR DESCRIPTION
**Pull request by timhae**
the examples have different puzzle size descriptions compared to the actual instances.

### CODE REVIEW

**Comment by daajoe** [comment]
@rkkautsar: can you check which version the validator used and unify then? I think more standard is 9x9 (so the domain size)

**Comment by rkkautsar** [comment]
@daajoe actually the validator does not consider the defined size and instead parse the board directly (e.g. count the number of `|` separator). So it doesn't matter whether it's 3x3 or 9x9. I agree with the need of consistency.

**Comment by daajoe** [comment]
Can you change all remaining instances then to 9x9?

**Comment by rkkautsar** [comment]
Yes. I'll merge this PR then since it already cover the sample instances. They should all be consistent now.

As for the full test instances I can provide a script to transform it later since I think they originally use the square-rooted version (i.e. 3x3 instead of 9x9).

**Comment by daajoe** [comment]
Many thx.

**Pull request merged**
